// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAfCReDBElJ2Nh3WGm6CE-bGI02TGGOxw',
    appId: '1:62473440884:web:a1b2c3d4e5f6g7h8i9j0k1',
    messagingSenderId: '62473440884',
    projectId: 'promptsat',
    authDomain: 'promptsat.firebaseapp.com',
    storageBucket: 'promptsat.appspot.com',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAfCReDBElJ2Nh3WGm6CE-bGI02TGGOxw',
    appId: '1:62473440884:android:9006baa79a628e28598b21',
    messagingSenderId: '62473440884',
    projectId: 'promptsat',
    storageBucket: 'promptsat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOQdSzNoe84MRHA-s9NKWSqndblkHj19Y',
    appId: '1:62473440884:ios:520c5d7332ad2926598b21',
    messagingSenderId: '62473440884',
    projectId: 'promptsat',
    storageBucket: 'promptsat.firebasestorage.app',
    iosBundleId: 'com.example.tabure',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAfCReDBElJ2Nh3WGm6CE-bGI02TGGOxw',
    appId: '1:62473440884:ios:a1b2c3d4e5f6g7h8i9j0k1l2m3',
    messagingSenderId: '62473440884',
    projectId: 'promptsat',
    storageBucket: 'promptsat.appspot.com',
    iosBundleId: 'com.tabure.app',
  );
}